version: "2.1"
services:
  vpn_wireguard:
    image: linuxserver/wireguard:latest
    ports: 
      - 5001:5001

  backend:
    build: backend/
    ports: 
      - 5000:5000
    depends_on:
      - vpn_wireguard